[package]
name = "iolite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanoid = "0.4.0"
once_cell = "1.19.0"
proptest = "1.4.0"
regex = "1.10.4"
